import os
import sys
import math
from snakemake.utils import min_version

min_version("7.32")

samples = list(config.keys())
print(f"Samples: {samples}")


include: "rules/common.smk"
include: "rules/ccs.smk"


rule all:
    input:
        expand(rules.merge_ccs_chunks.output, sm=samples),
