default-resources:
  - disk_mb=8096
  - mem_mb=8096
  - time=600
  - gpus=0
#scheduler: greedy
rerun-incomplete: True
rerun-triggers: mtime
restart-times: 0
show-failed-logs: True
quiet: progress
# reason: True
# printshellcmds: True
use-conda: True
use-singularity: True
